title:            'No Turning Back: Ten Years After Occupy'
description:      ''
url:              ''
baseurl:          /occupy
logo:             /assets/logo.png
copyright:        ''

permalink:        pretty
theme:            wax_theme
source:           source
incremental:      true

collections:
  themes:
    output: true
    layout: theme
    metadata:
      source: themes.csv
  declarations:
    output: true
    layout: declaration
    metadata:
      source: declarations.csv
  items:
    output: true
    layout: occupy_item
    metadata:
      source: occupy.csv
      split:
        themes: ','
        declarations: ','
    images:
      source: images

menu:
  - label: Home
    link: /
  - label: About
    sub:
      - label: About the Exhibit
        link: /about/
      - label: Bibliography
        link: /bibliography/
  - label: Declaration of the Occupation
    link: /declarations/
  - label: Browse the Collection
    sub:
      - label: By Theme
        link: /themes/
      - label: By Object Type
        link: /types/
      - label: By Declaration
        link : /declarations/#read-the-document-and-browse-related-items


footer:
  links:
    - label: NYU Special Collections
      link: 'https://library.nyu.edu/locations/special-collections-center/'

sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
  - Dockerfile
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'

kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false
