title:            Occupy Wall Street
description:      ''
url:              ''
baseurl:          /occupy
logo:             /assets/logo.png

permalink:        pretty
incremental:      true
theme:            wax_theme

collections:
  occupy:
    output: true
    layout: occupy_item
    metadata:
      source: occupy.csv
    images:
      source: images

menu:
  - label: About
    link: /about/
  - label: Get Involved
    link: /get-involved/
  - label: Resources
    link: /resources/
  - label: Browse the Exhibition
    link: /exhibition/

footer:
  links:
    - label: NYU Special Collections
      link: 'https://library.nyu.edu/locations/special-collections-center/'

sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
  - Dockerfile
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'

kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false
