name: ci:deploy
on:
  push:
    branches:
      - feature/dlts-iiif-api 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BASEURL: '/occupy'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: install
        run: gem install bundler && bundle
      - name: test
        run: bundle exec rake test
      - name: prod build
        run: bundle exec rake reset && bundle exec rake build
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: marii.hosting.nyu.edu
          username: ${{secrets.FTP_STAGE_USERNAME}}@marii.hosting.nyu.edu
          password: ${{secrets.FTP_STAGE_PASSWORD}}
          local-dir: ./_site/
          server-dir: occupy/
          state-name: ./.ftp-deploy-sync-state.json
